name: Publish Docker Jenkins Images
trigger:
  batch: true
  branches:
    include:
      - master
pr: none

variables:
  acrName: hmctspublic
  targetRegistry: hmctspublic.azurecr.io
  serviceConnection: 'azurerm-prod'

jobs:
  - job:
    condition: >
      and(
          succeeded(),
          startsWith(variables['Build.SourceBranch'], 'refs/heads/master')
        )
    pool:
      vmImage: 'Ubuntu 16.04'
    strategy:
      maxParallel: 2
      matrix:
        jenkins-master:
          taskName: jenkins-master
          dockerfile: Dockerfile
          type: master
        jenkins-agent:
          taskName: jenkins-agent
          dockerfile: Dockerfile
          type: agent
    steps:
      - task: AzureCLI@1
        displayName: 'Publish base image $(taskName)'
        inputs:
          azureSubscription: $(serviceConnection)
          scriptLocation: 'inlineScript'
          inlineScript: |
            az acr login --name $(acrName)
            docker build -t $(targetRegistry)/jenkins/$(type) -f $(type)/$(dockerfile) $(type)/
            docker push $(targetRegistry)/jenkins/$(type)
