version: 1
update_configs:
  - package_manager: "docker"
    directory: "/jenkins"
    update_schedule: "daily"
  - package_manager: "docker"
    directory: "/jenkins-agent"
    update_schedule: "daily"
