name: cd

on:
  workflow_dispatch:
  push:
    branches: "master"

jobs:
  main:
    runs-on: ubuntu-20.04
    env:
      AZURE_CONTAINER_REGISTRY_URL: hmctspublic.azurecr.io
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Azure Container Repository
        uses: docker/login-action@v1
        with:
          registry: ${{ env.AZURE_CONTAINER_REGISTRY_URL }}
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}
      - run: |
          echo JENKINS_VERSION=$(grep "FROM jenkins" jenkins/Dockerfile | cut -d: -f2 | cut -d- -f1) >> $GITHUB_ENV
      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./jenkins
          push: true
          tags: ${{ env.AZURE_CONTAINER_REGISTRY_URL }}/jenkins/jenkins:${{ env.JENKINS_VERSION }}-${{ github.run_number }}
