name: Update Jenkins plugins

on:
  workflow_dispatch:
  push:
    branches:
     - 'master'
  schedule:
    # * is a special character in YAML, so you have to quote this string
    - cron: '30 8 * * TUE'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
      - run: ./bin/update-plugins-no-docker.sh
        name: Update plugins
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: 'Update Jenkins plugins'
          author: 'GitHub <41898282+github-actions[bot]@users.noreply.github.com>'
          signoff: true
          title: 'Update Jenkins plugins'
